// 04_vue/src/App.vue
<template>
  <div class="site">
    <form class="todo-form" @submit.prevent="addTodo">
      <label for="todo-input" class="todo-form__label">What do you want to do?</label>
      <input id="todo-input" type="text" class="todo-form__input" name="todo" required v-model="todo">
      <button type="submit" class="todo-form__submit btn">Add to list</button>
    </form>

    <main class="todo-section">
      <ul class="todo-list">
        <li
          v-for="todoItem in todos"
          :key="todoItem.description"
          class="todo-list__item">
          <label class="todo-list__label">
            <input
              v-model="todoItem.done"
              @change="saveState"
              type="checkbox"
              class="todo-list__checkbox">
            <span
              :class="[todoItem.done ? 'todo-list__description--done' : '']"
              class="todo-list__description"
            >{{todoItem.description}}</span>
          </label>
          <button
            @click="removeTodo(todoItem)"
            class="todo-list__remove btn btn--danger">Remove</button>
        </li>
      </ul>
    </main>
  </div>
</template>

<script>
import Vue from 'vue'

const KEY = 'todos'

export default {
  name: 'App',
  data() {
    return {
      todo: '',
      todos: []
    }
  },
  mounted() {
    this.loadState()
  },
  methods: {
    saveState() {
      localStorage.setItem(KEY, JSON.stringify(this.todos))
    },
    loadState() {
      const storeTodos = localStorage.getItem(KEY)

      if (storeTodos) {
        Vue.set(this, 'todos', JSON.parse(storeTodos))
      }
    },
    addTodo() {
      const newTodo = {
        done: false,
        description: this.todo
      }

      this.todos.push(newTodo)

      this.todo = ''

      this.saveState()
    },
    removeTodo(todoItem) {
      const idx = this.todos.indexOf(todoItem)

      if (idx >= 0) {
        this.todos.splice(idx, 1)
      }

      this.saveState()
    }
  }
}
</script>

// 03_angular/src/app/app.component.ts
import { Component, OnChanges, OnInit, SimpleChanges } from '@angular/core';

const KEY = 'todos'

type TodoItem = {
  done: boolean
  description: string
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  todo: string = ''
  todos: TodoItem[] = []

  ngOnInit(): void {
    this.loadState()
  }

  saveState() {
    localStorage.setItem(KEY, JSON.stringify(this.todos))
  }

  loadState() {
    const todos = localStorage.getItem(KEY)

    if (todos) {
      this.todos = [...JSON.parse(todos)]
    }
  }

  addTodo(event?: Event) {
    event?.preventDefault()

    const newTodo: TodoItem = {
      done: false,
      description: this.todo
    }

    this.todos = [...this.todos, newTodo]

    this.todo = ''

    this.saveState()
  }

  removeItem(todoItem: TodoItem) {
    const idx = this.todos.indexOf(todoItem)

    if (idx >= 0) {
      this.todos.splice(idx, 1)
    }

    this.saveState()
  }
}

<div class="site">
  <form class="todo-form" (submit)="addTodo()">
    <label for="todo-input" class="todo-form__label">What do you want to do?</label>
    <input id="todo-input" type="text" class="todo-form__input" name="todo" required [(ngModel)]="todo">
    <button type="submit" class="todo-form__submit btn">Add to list</button>
  </form>

  <main class="todo-section">
    <ul class="todo-list">
      <li class="todo-list__item" *ngFor="let todoItem of todos">
        <label class="todo-list__label">
          <input
            type="checkbox"
            class="todo-list__checkbox"
            [(ngModel)]="todoItem.done"
            (change)="saveState()">
          <span
            class="todo-list__description"
            [class.todo-list__description--done]="todoItem.done"
          >{{todoItem.description}}</span>
        </label>
        <button
          class="todo-list__remove btn btn--danger"
          (click)="removeItem(todoItem)">Remove</button>
      </li>
    </ul>
  </main>
</div>
